In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/playground-series-s4e6/sample_submission.csv
/kaggle/input/playground-series-s4e6/train.csv
/kaggle/input/playground-series-s4e6/test.csv


In [2]:
import tensorflow as tf
import numpy as np
import pandas as pd
import sklearn
import random
import os
import matplotlib.pyplot as plt

2024-06-26 13:29:08.716132: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-06-26 13:29:08.716227: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-06-26 13:29:08.834027: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


In [3]:
train_data=pd.read_csv("/kaggle/input/playground-series-s4e6/train.csv")
test_data=pd.read_csv("/kaggle/input/playground-series-s4e6/test.csv")
train_data.head()

id  Marital status  Application mode  Application order  Course  \
0   0               1                 1                  1    9238   
1   1               1                17                  1    9238   
2   2               1                17                  2    9254   
3   3               1                 1                  3    9500   
4   4               1                 1                  2    9500   

   Daytime/evening attendance  Previous qualification  \
0                           1                       1   
1                           1                       1   
2                           1                       1   
3                           1                       1   
4                           1                       1   

   Previous qualification (grade)  Nacionality  Mother's qualification  ...  \
0                           126.0            1                       1  ...   
1                           125.0            1                      19  ...   
2                           137.0            1                       3  ...   
3                           131.0            1                      19  ...   
4                           132.0            1                      19  ...   

   Curricular units 2nd sem (credited)  Curricular units 2nd sem (enrolled)  \
0                                    0                                    6   
1                                    0                                    6   
2                                    0                                    6   
3                                    0                                    8   
4                                    0                                    7   

   Curricular units 2nd sem (evaluations)  \
0                                       7   
1                                       9   
2                                       0   
3                                      11   
4                                      12   

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
0                                    6                         12.428571   
1                                    0                          0.000000   
2                                    0                          0.000000   
3                                    7                         12.820000   
4                                    6                         12.933333   

   Curricular units 2nd sem (without evaluations)  Unemployment rate  \
0                                               0               11.1   
1                                               0               11.1   
2                                               0               16.2   
3                                               0               11.1   
4                                               0                7.6   

   Inflation rate   GDP    Target  
0             0.6  2.02  Graduate  
1             0.6  2.02   Dropout  
2             0.3 -0.92   Dropout  
3             0.6  2.02  Enrolled  
4             2.6  0.32  Graduate  

[5 rows x 38 columns]

In [60]:
test_data.head()

id  Marital status  Application mode  Application order  Course  \
0  76518               1                 1                  1    9500   
1  76519               1                 1                  1    9238   
2  76520               1                 1                  1    9238   
3  76521               1                44                  1    9147   
4  76522               1                39                  1    9670   

   Daytime/evening attendance  Previous qualification  \
0                           1                       1   
1                           1                       1   
2                           1                       1   
3                           1                      39   
4                           1                       1   

   Previous qualification (grade)  Nacionality  Mother's qualification  ...  \
0                           141.0            1                       3  ...   
1                           128.0            1                       1  ...   
2                           118.0            1                       1  ...   
3                           130.0            1                       1  ...   
4                           110.0            1                       1  ...   

   Curricular units 1st sem (without evaluations)  \
0                                               0   
1                                               0   
2                                               0   
3                                               0   
4                                               0   

   Curricular units 2nd sem (credited)  Curricular units 2nd sem (enrolled)  \
0                                    0                                    8   
1                                    0                                    6   
2                                    0                                    6   
3                                    3                                    8   
4                                    0                                    6   

   Curricular units 2nd sem (evaluations)  \
0                                       0   
1                                       6   
2                                      11   
3                                      14   
4                                       9   

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
0                                    0                          0.000000   
1                                    6                         13.500000   
2                                    5                         11.000000   
3                                    5                         11.000000   
4                                    4                         10.666667   

   Curricular units 2nd sem (without evaluations)  Unemployment rate  \
0                                               0               13.9   
1                                               0               11.1   
2                                               0               15.5   
3                                               0                8.9   
4                                               2                7.6   

   Inflation rate   GDP  
0            -0.3  0.79  
1             0.6  2.02  
2             2.8 -4.06  
3             1.4  3.51  
4             2.6  0.32  

[5 rows x 37 columns]

In [4]:

train_data.head()

id  Marital status  Application mode  Application order  Course  \
0   0               1                 1                  1    9238   
1   1               1                17                  1    9238   
2   2               1                17                  2    9254   
3   3               1                 1                  3    9500   
4   4               1                 1                  2    9500   

   Daytime/evening attendance  Previous qualification  \
0                           1                       1   
1                           1                       1   
2                           1                       1   
3                           1                       1   
4                           1                       1   

   Previous qualification (grade)  Nacionality  Mother's qualification  ...  \
0                           126.0            1                       1  ...   
1                           125.0            1                      19  ...   
2                           137.0            1                       3  ...   
3                           131.0            1                      19  ...   
4                           132.0            1                      19  ...   

   Curricular units 2nd sem (credited)  Curricular units 2nd sem (enrolled)  \
0                                    0                                    6   
1                                    0                                    6   
2                                    0                                    6   
3                                    0                                    8   
4                                    0                                    7   

   Curricular units 2nd sem (evaluations)  \
0                                       7   
1                                       9   
2                                       0   
3                                      11   
4                                      12   

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
0                                    6                         12.428571   
1                                    0                          0.000000   
2                                    0                          0.000000   
3                                    7                         12.820000   
4                                    6                         12.933333   

   Curricular units 2nd sem (without evaluations)  Unemployment rate  \
0                                               0               11.1   
1                                               0               11.1   
2                                               0               16.2   
3                                               0               11.1   
4                                               0                7.6   

   Inflation rate   GDP    Target  
0             0.6  2.02  Graduate  
1             0.6  2.02   Dropout  
2             0.3 -0.92   Dropout  
3             0.6  2.02  Enrolled  
4             2.6  0.32  Graduate  

[5 rows x 38 columns]

In [5]:
X_train=train_data.drop(columns=["Target"])
X_train.head()

id  Marital status  Application mode  Application order  Course  \
0   0               1                 1                  1    9238   
1   1               1                17                  1    9238   
2   2               1                17                  2    9254   
3   3               1                 1                  3    9500   
4   4               1                 1                  2    9500   

   Daytime/evening attendance  Previous qualification  \
0                           1                       1   
1                           1                       1   
2                           1                       1   
3                           1                       1   
4                           1                       1   

   Previous qualification (grade)  Nacionality  Mother's qualification  ...  \
0                           126.0            1                       1  ...   
1                           125.0            1                      19  ...   
2                           137.0            1                       3  ...   
3                           131.0            1                      19  ...   
4                           132.0            1                      19  ...   

   Curricular units 1st sem (without evaluations)  \
0                                               0   
1                                               0   
2                                               0   
3                                               0   
4                                               0   

   Curricular units 2nd sem (credited)  Curricular units 2nd sem (enrolled)  \
0                                    0                                    6   
1                                    0                                    6   
2                                    0                                    6   
3                                    0                                    8   
4                                    0                                    7   

   Curricular units 2nd sem (evaluations)  \
0                                       7   
1                                       9   
2                                       0   
3                                      11   
4                                      12   

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
0                                    6                         12.428571   
1                                    0                          0.000000   
2                                    0                          0.000000   
3                                    7                         12.820000   
4                                    6                         12.933333   

   Curricular units 2nd sem (without evaluations)  Unemployment rate  \
0                                               0               11.1   
1                                               0               11.1   
2                                               0               16.2   
3                                               0               11.1   
4                                               0                7.6   

   Inflation rate   GDP  
0             0.6  2.02  
1             0.6  2.02  
2             0.3 -0.92  
3             0.6  2.02  
4             2.6  0.32  

[5 rows x 37 columns]

In [6]:
y_train=train_data["Target"]
y_train

0        Graduate
1         Dropout
2         Dropout
3        Enrolled
4        Graduate
           ...   
76513    Graduate
76514    Graduate
76515    Enrolled
76516     Dropout
76517    Graduate
Name: Target, Length: 76518, dtype: object

In [7]:
X_test=test_data
X_test.describe()

id  Marital status  Application mode  Application order  \
count   51012.000000    51012.000000      51012.000000       51012.000000   
mean   102023.500000        1.109092         16.067102           1.648161   
std     14726.040303        0.438084         16.654196           1.235666   
min     76518.000000        1.000000          1.000000           0.000000   
25%     89270.750000        1.000000          1.000000           1.000000   
50%    102023.500000        1.000000         17.000000           1.000000   
75%    114776.250000        1.000000         39.000000           2.000000   
max    127529.000000        6.000000         53.000000           9.000000   

             Course  Daytime/evening attendance  Previous qualification  \
count  51012.000000                51012.000000            51012.000000   
mean    9026.304556                    0.918313                3.635007   
std     1751.328311                    0.273889                8.577250   
min       33.000000                    0.000000                1.000000   
25%     9119.000000                    1.000000                1.000000   
50%     9254.000000                    1.000000                1.000000   
75%     9670.000000                    1.000000                1.000000   
max     9991.000000                    1.000000               43.000000   

       Previous qualification (grade)  Nacionality  Mother's qualification  \
count                    51012.000000  51012.00000            51012.000000   
mean                       132.328001      1.20009               19.913275   
std                         10.885679      3.26473               15.383823   
min                         95.000000      1.00000                1.000000   
25%                        125.000000      1.00000                1.000000   
50%                        133.100000      1.00000               19.000000   
75%                        139.000000      1.00000               37.000000   
max                        190.000000    109.00000               44.000000   

       ...  Curricular units 1st sem (without evaluations)  \
count  ...                                    51012.000000   
mean   ...                                        0.057810   
std    ...                                        0.403434   
min    ...                                        0.000000   
25%    ...                                        0.000000   
50%    ...                                        0.000000   
75%    ...                                        0.000000   
max    ...                                       12.000000   

       Curricular units 2nd sem (credited)  \
count                         51012.000000   
mean                              0.129283   
std                               0.877250   
min                               0.000000   
25%                               0.000000   
50%                               0.000000   
75%                               0.000000   
max                              19.000000   

       Curricular units 2nd sem (enrolled)  \
count                         51012.000000   
mean                              5.944131   
std                               1.599746   
min                               0.000000   
25%                               5.000000   
50%                               6.000000   
75%                               6.000000   
max                              23.000000   

       Curricular units 2nd sem (evaluations)  \
count                            51012.000000   
mean                                 7.274092   
std                                  3.433149   
min                                  0.000000   
25%                                  6.000000   
50%                                  8.000000   
75%                                  9.000000   
max                                 33.000000   

       Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
count                         5101

In [8]:
X_train.describe()

id  Marital status  Application mode  Application order  \
count  76518.000000    76518.000000      76518.000000       76518.000000   
mean   38258.500000        1.111934         16.054419           1.644410   
std    22088.988286        0.441669         16.682337           1.229645   
min        0.000000        1.000000          1.000000           0.000000   
25%    19129.250000        1.000000          1.000000           1.000000   
50%    38258.500000        1.000000         17.000000           1.000000   
75%    57387.750000        1.000000         39.000000           2.000000   
max    76517.000000        6.000000         53.000000           9.000000   

             Course  Daytime/evening attendance  Previous qualification  \
count  76518.000000                76518.000000            76518.000000   
mean    9001.286377                    0.915314                3.658760   
std     1803.438531                    0.278416                8.623774   
min       33.000000                    0.000000                1.000000   
25%     9119.000000                    1.000000                1.000000   
50%     9254.000000                    1.000000                1.000000   
75%     9670.000000                    1.000000                1.000000   
max     9991.000000                    1.000000               43.000000   

       Previous qualification (grade)   Nacionality  Mother's qualification  \
count                    76518.000000  76518.000000            76518.000000   
mean                       132.378766      1.226600               19.837633   
std                         10.995328      3.392183               15.399456   
min                         95.000000      1.000000                1.000000   
25%                        125.000000      1.000000                1.000000   
50%                        133.100000      1.000000               19.000000   
75%                        140.000000      1.000000               37.000000   
max                        190.000000    109.000000               44.000000   

       ...  Curricular units 1st sem (without evaluations)  \
count  ...                                     76518.00000   
mean   ...                                         0.05796   
std    ...                                         0.40849   
min    ...                                         0.00000   
25%    ...                                         0.00000   
50%    ...                                         0.00000   
75%    ...                                         0.00000   
max    ...                                        12.00000   

       Curricular units 2nd sem (credited)  \
count                         76518.000000   
mean                              0.137053   
std                               0.933830   
min                               0.000000   
25%                               0.000000   
50%                               0.000000   
75%                               0.000000   
max                              19.000000   

       Curricular units 2nd sem (enrolled)  \
count                         76518.000000   
mean                              5.933414   
std                               1.627182   
min                               0.000000   
25%                               5.000000   
50%                               6.000000   
75%                               6.000000   
max                              23.000000   

       Curricular units 2nd sem (evaluations)  \
count                            76518.000000   
mean                                 7.234468   
std                                  3.503040   
min                                  0.000000   
25%                                  6.000000   
50%                                  7.000000   
75%                                  9.000000   
max                                 33.000000   

       Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
count                         765

In [9]:
"""from sklearn.compose import make_column_transformer
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
print(X_train.columns)
print(len(X_train.columns))
#for i in range(len(X_train.columns)):
#    print(X_train.header())
print(X_train.columns.dtype)
pre = train_data.drop("id", axis=1)
pre.head()"""

'from sklearn.compose import make_column_transformer\nfrom sklearn.preprocessing import MinMaxScaler, OneHotEncoder\nprint(X_train.columns)\nprint(len(X_train.columns))\n#for i in range(len(X_train.columns)):\n#    print(X_train.header())\nprint(X_train.columns.dtype)\npre = train_data.drop("id", axis=1)\npre.head()'

In [10]:
"""ct = make_column_transformer(
    (MinMaxScaler(),["id", "Marital status", "Application mode", "Application order",
       "Course", "Daytime/evening attendance", "Previous qualification",
       "Previous qualification (grade)", "Nacionality",
       "Mother's qualification", "Father's qualification",
       "Mother's occupation","Father's occupation", "Admission grade",
       "Displaced", "Educational special needs", "Debtor",
       "Tuition fees up to date", "Gender", "Scholarship holder",
       "Age at enrollment", "International",
       "Curricular units 1st sem (credited)",
       "Curricular units 1st sem (enrolled)",
       "Curricular units 1st sem (evaluations)",
       "Curricular units 1st sem (approved)",
       "Curricular units 1st sem (grade)",
       "Curricular units 1st sem (without evaluations)",
       "Curricular units 2nd sem (credited)",
       "Curricular units 2nd sem (enrolled)",
       "Curricular units 2nd sem (evaluations)",
       "Curricular units 2nd sem (approved)",
       "Curricular units 2nd sem (grade)",
       "Curricular units 2nd sem (without evaluations)", "Unemployment rate",
       "Inflation rate", "GDP"]), # get all values between 0 and 1
    (OneHotEncoder(handle_unknown="ignore"), ["Target"])
)
"""

'ct = make_column_transformer(\n    (MinMaxScaler(),["id", "Marital status", "Application mode", "Application order",\n       "Course", "Daytime/evening attendance", "Previous qualification",\n       "Previous qualification (grade)", "Nacionality",\n       "Mother\'s qualification", "Father\'s qualification",\n       "Mother\'s occupation","Father\'s occupation", "Admission grade",\n       "Displaced", "Educational special needs", "Debtor",\n       "Tuition fees up to date", "Gender", "Scholarship holder",\n       "Age at enrollment", "International",\n       "Curricular units 1st sem (credited)",\n       "Curricular units 1st sem (enrolled)",\n       "Curricular units 1st sem (evaluations)",\n       "Curricular units 1st sem (approved)",\n       "Curricular units 1st sem (grade)",\n       "Curricular units 1st sem (without evaluations)",\n       "Curricular units 2nd sem (credited)",\n       "Curricular units 2nd sem (enrolled)",\n       "Curricular units 2nd sem (evaluations)",\n    

In [11]:
train_data.head()

id  Marital status  Application mode  Application order  Course  \
0   0               1                 1                  1    9238   
1   1               1                17                  1    9238   
2   2               1                17                  2    9254   
3   3               1                 1                  3    9500   
4   4               1                 1                  2    9500   

   Daytime/evening attendance  Previous qualification  \
0                           1                       1   
1                           1                       1   
2                           1                       1   
3                           1                       1   
4                           1                       1   

   Previous qualification (grade)  Nacionality  Mother's qualification  ...  \
0                           126.0            1                       1  ...   
1                           125.0            1                      19  ...   
2                           137.0            1                       3  ...   
3                           131.0            1                      19  ...   
4                           132.0            1                      19  ...   

   Curricular units 2nd sem (credited)  Curricular units 2nd sem (enrolled)  \
0                                    0                                    6   
1                                    0                                    6   
2                                    0                                    6   
3                                    0                                    8   
4                                    0                                    7   

   Curricular units 2nd sem (evaluations)  \
0                                       7   
1                                       9   
2                                       0   
3                                      11   
4                                      12   

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
0                                    6                         12.428571   
1                                    0                          0.000000   
2                                    0                          0.000000   
3                                    7                         12.820000   
4                                    6                         12.933333   

   Curricular units 2nd sem (without evaluations)  Unemployment rate  \
0                                               0               11.1   
1                                               0               11.1   
2                                               0               16.2   
3                                               0               11.1   
4                                               0                7.6   

   Inflation rate   GDP    Target  
0             0.6  2.02  Graduate  
1             0.6  2.02   Dropout  
2             0.3 -0.92   Dropout  
3             0.6  2.02  Enrolled  
4             2.6  0.32  Graduate  

[5 rows x 38 columns]

In [17]:
y_train.head()

0    Graduate
1     Dropout
2     Dropout
3    Enrolled
4    Graduate
Name: Target, dtype: object

In [18]:
"""ct.fit(X)
X_train_normal = ct.transform(X)
X_test_normal = ct.transform(y)"""

'ct.fit(X)\nX_train_normal = ct.transform(X)\nX_test_normal = ct.transform(y)'

In [19]:
"""from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.2, random_state=42)
ct.fit(X_train)
X_train_normal = ct.transform(X_train)
X_test_normal = ct.transform(X_test)"""

'from sklearn.model_selection import train_test_split\nX_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.2, random_state=42)\nct.fit(X_train)\nX_train_normal = ct.transform(X_train)\nX_test_normal = ct.transform(X_test)'

In [21]:
"""X = train_data.drop("Target", axis=1)
y = train_data["Target"]
X.head()"""

'X = train_data.drop("Target", axis=1)\ny = train_data["Target"]\nX.head()'

In [22]:
"""from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
ct.fit(X_train)
X_train_normal = ct.transform(X_train)
X_test_normal = ct.transform(X_test)"""

'from sklearn.model_selection import train_test_split\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\nct.fit(X_train)\nX_train_normal = ct.transform(X_train)\nX_test_normal = ct.transform(X_test)'

In [23]:

#X_train.loc[2]    

In [24]:
#X_train_normal[2]

In [25]:
#X_train_normal.shape, X_train.shape

In [26]:
#y_train.head(

In [27]:
"""ct2 = make_column_transformer(
    (OneHotEncoder, ["Target"])
)"""

'ct2 = make_column_transformer(\n    (OneHotEncoder, ["Target"])\n)'

In [28]:
#y_train_normal = ct2.transform(y_train)

In [12]:
X_train.head()

id  Marital status  Application mode  Application order  Course  \
0   0               1                 1                  1    9238   
1   1               1                17                  1    9238   
2   2               1                17                  2    9254   
3   3               1                 1                  3    9500   
4   4               1                 1                  2    9500   

   Daytime/evening attendance  Previous qualification  \
0                           1                       1   
1                           1                       1   
2                           1                       1   
3                           1                       1   
4                           1                       1   

   Previous qualification (grade)  Nacionality  Mother's qualification  ...  \
0                           126.0            1                       1  ...   
1                           125.0            1                      19  ...   
2                           137.0            1                       3  ...   
3                           131.0            1                      19  ...   
4                           132.0            1                      19  ...   

   Curricular units 1st sem (without evaluations)  \
0                                               0   
1                                               0   
2                                               0   
3                                               0   
4                                               0   

   Curricular units 2nd sem (credited)  Curricular units 2nd sem (enrolled)  \
0                                    0                                    6   
1                                    0                                    6   
2                                    0                                    6   
3                                    0                                    8   
4                                    0                                    7   

   Curricular units 2nd sem (evaluations)  \
0                                       7   
1                                       9   
2                                       0   
3                                      11   
4                                      12   

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
0                                    6                         12.428571   
1                                    0                          0.000000   
2                                    0                          0.000000   
3                                    7                         12.820000   
4                                    6                         12.933333   

   Curricular units 2nd sem (without evaluations)  Unemployment rate  \
0                                               0               11.1   
1                                               0               11.1   
2                                               0               16.2   
3                                               0               11.1   
4                                               0                7.6   

   Inflation rate   GDP  
0             0.6  2.02  
1             0.6  2.02  
2             0.3 -0.92  
3             0.6  2.02  
4             2.6  0.32  

[5 rows x 37 columns]

In [13]:
y_train.head()

0    Graduate
1     Dropout
2     Dropout
3    Enrolled
4    Graduate
Name: Target, dtype: object

In [14]:
X_train.shape,y_train.shape

((76518, 37), (76518,))

In [ ]:
:
        

In [15]:
"""y_train1 = pd.get_dummies(y_train)
print(y_train1)"""

'y_train1 = pd.get_dummies(y_train)\nprint(y_train1)'

In [16]:
t=[]
for i in y_train:
    if i == "Graduate":
        t.append(0)
    elif i == "Enrolled":
        t.append(1)
    elif i == "Dropout":
        t.append(2)

In [17]:
print(t)

[0, 2, 2, 1, 0, 2, 0, 0, 2, 0, 2, 2, 1, 2, 2, 0, 2, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 1, 0, 2, 0, 2, 2, 0, 1, 2, 2, 2, 1, 2, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 1, 0, 0, 2, 0, 1, 1, 2, 2, 1, 2, 2, 0, 2, 1, 0, 1, 2, 0, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 1, 2, 0, 0, 2, 1, 2, 0, 1, 1, 0, 2, 2, 0, 0, 1, 0, 2, 0, 2, 2, 0, 1, 2, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 1, 0, 1, 0, 0, 0, 0, 2, 2, 2, 2, 1, 0, 2, 1, 2, 2, 2, 2, 2, 2, 0, 0, 1, 0, 2, 1, 2, 2, 2, 1, 0, 0, 2, 2, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 2, 1, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 1, 2, 1, 2, 0, 0, 0, 0, 1, 0, 0, 2, 0, 2, 0, 2, 0, 2, 2, 1, 1, 0, 0, 1, 2, 0, 0, 0, 0, 2, 0, 1, 0, 2, 1, 0, 1, 0, 0, 0, 0, 2, 2, 2, 2, 0, 2, 2, 2, 1, 1, 1, 0, 1, 0, 0, 2, 0, 0, 1, 1, 2, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 0, 1, 2, 2, 2, 1, 0, 2, 1, 0, 2, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 1, 2, 2, 0, 2, 2, 0, 0, 2, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 2, 1, 1, 2, 0, 0, 0, 1, 

In [18]:
tt=tf.Variable(t)
tt.shape
print(tt)

<tf.Variable 'Variable:0' shape=(76518,) dtype=int32, numpy=array([0, 2, 2, ..., 1, 2, 0], dtype=int32)>


In [31]:
tf.random.set_seed(42)

model=tf.keras.Sequential([
    tf.keras.layers.Dense(100,activation="relu"),
    tf.keras.layers.Dense(64,activation="relu"),
    tf.keras.layers.Dense(3,activation="softmax")
])

model.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy(),
             optimizer=tf.keras.optimizers.Adam(),
             metrics=["accuracy"])

In [32]:
model.fit(X_train,tt, epochs=50) 

Epoch 1/50
2392/2392 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.4245 - loss: 130.8151
Epoch 2/50
2392/2392 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.5516 - loss: 38.6521
Epoch 3/50
2392/2392 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.6041 - loss: 22.6482
Epoch 4/50
2392/2392 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.6270 - loss: 16.8293
Epoch 5/50
2392/2392 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.6479 - loss: 12.5355
Epoch 6/50
2392/2392 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.6712 - loss: 8.2631
Epoch 7/50
2392/2392 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - accuracy: 0.6796 - loss: 5.8670
Epoch 8/50
2392/2392 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.6865 - loss: 4.3011
Epoch 9/50
2392/2392 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.6931 - loss: 2.7360
Epoch 10/50
2392/2392 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.7048 - loss: 1.7892
Epoch 11/50
2392/2392 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.7129 - loss: 1.1701
Epoch 12/50
2392/2392 ━━

In [33]:
model.save("model.h5")

In [35]:
results=model.predict(X_test)

1595/1595 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step


In [36]:
results

array([[5.2744831e-04, 4.4434704e-02, 9.5503783e-01],
       [8.2842433e-01, 1.2922041e-01, 4.2355355e-02],
       [3.7002909e-01, 4.8204234e-01, 1.4792863e-01],
       ...,
       [1.3474438e-01, 2.7117956e-01, 5.9407616e-01],
       [3.0201362e-02, 5.1762396e-01, 4.5217463e-01],
       [1.9230829e-01, 1.9415762e-01, 6.1353409e-01]], dtype=float32)

In [37]:
results.shape

(51012, 3)

In [39]:
predict=results.round()

In [40]:
predict.shape
    

(51012, 3)

In [41]:
predict = tf.cast(predict, dtype=tf.int32)

In [42]:
predict.shape

TensorShape([51012, 3])

In [43]:
j=1
l=[]
for i in predict:
  print(i)
  indexes = tf.where(tf.equal(i, 1))
  print(indexes.numpy().squeeze())
  l.append([j,indexes.numpy().squeeze()])
  j=j+1

tf.Tensor([0 0 1], shape=(3,), dtype=int32)
2
tf.Tensor([1 0 0], shape=(3,), dtype=int32)
0
tf.Tensor([0 0 0], shape=(3,), dtype=int32)
[]
tf.Tensor([0 1 0], shape=(3,), dtype=int32)
1
tf.Tensor([0 1 0], shape=(3,), dtype=int32)
1
tf.Tensor([1 0 0], shape=(3,), dtype=int32)
0
tf.Tensor([1 0 0], shape=(3,), dtype=int32)
0
tf.Tensor([1 0 0], shape=(3,), dtype=int32)
0
tf.Tensor([0 1 0], shape=(3,), dtype=int32)
1
tf.Tensor([1 0 0], shape=(3,), dtype=int32)
0
tf.Tensor([1 0 0], shape=(3,), dtype=int32)
0
tf.Tensor([1 0 0], shape=(3,), dtype=int32)
0
tf.Tensor([1 0 0], shape=(3,), dtype=int32)
0
tf.Tensor([0 1 0], shape=(3,), dtype=int32)
1
tf.Tensor([0 0 1], shape=(3,), dtype=int32)
2
tf.Tensor([0 1 0], shape=(3,), dtype=int32)
1
tf.Tensor([1 0 0], shape=(3,), dtype=int32)
0
tf.Tensor([1 0 0], shape=(3,), dtype=int32)
0
tf.Tensor([0 1 0], shape=(3,), dtype=int32)
1
tf.Tensor([1 0 0], shape=(3,), dtype=int32)
0
tf.Tensor([1 0 0], shape=(3,), dtype=int32)
0
tf.Tensor([0 0 1], shape=(3,), dt

In [ ]:
for i in l:
    if i == 0:
        

In [44]:
exit=pd.DataFrame(l)
col=["id","Target"]
exit.columns=col
exit.head()

id Target
0   1      2
1   2      0
2   3     []
3   4      1
4   5      1