In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
#lambda function
lam=lambda x : x+2
print(lam(3))

5


In [3]:
#map function
#this is lazy loading function 
#it takes on iteratables and function is applies the elements to list
print(list(map(lambda x : x%2,[1,2,3,4,5])))

[1, 0, 1, 0, 1]


In [4]:
# filter function it filters out all the data in list or iteratable depending on true or false
print(list(filter(lambda x :x%2==0,[1,2,3,4,5])))

[2, 4]


In [5]:
import random
print(random.randint(1,10))
print(random.choice(["saabir","ayesha"]))

6
saabir


In [6]:
import json
jsondata=json.dumps({
    "name":"saabir",
    "age":23
})

In [7]:
jsondata

'{"name": "saabir", "age": 23}'

In [8]:
jsonstr=json.loads(jsondata)
jsonstr

{'name': 'saabir', 'age': 23}

In [9]:
import time
import datetime
timenow1=datetime.datetime.now()
time.sleep(3)
timenow2=datetime.datetime.now()
print(timenow2-timenow1)

0:00:03.000396


In [10]:
time1=time.time()
time.sleep(4)
time2=time.time()
print(time2-time1)

4.000477075576782


In [11]:
#try except block
try:
    #a=b
    num=int(input("enter an integer"))
    result=1/num
except TypeError as ex:
    print(ex)
except ValueError as ex1:
    print(ex1)
except ZeroDivisionError as ex2:
    print(ex2)
except Exception as ex3:
    print(ex3)
else:
    print("No Errors")
    print(result)
finally:
    print("code executed \nerror or not code is executed")

enter an integer 4


No Errors
0.25
code executed 
error or not code is executed


In [12]:
#custom package or module
#attempt it in perosnal laptop

In [13]:
#print(dir(car))

In [14]:
#saabir.printdetails()

In [15]:
class BankAccount:
    def __init__(self,i,name,balance):
        self.i=i
        self.name=name
        self.balance=balance
    def deposit(self,amount):
        self.balance+=amount
        print("deposited suceesfully")
        self.printbalance()
    def withdraw(self,amount):
        if self.balance<amount:
            print("balance insufficent")
        else:
            self.balance-=amount
            print("amount withdrawn")
            self.printbalance()
    def printbalance(self):
        print(self.balance)
b1=BankAccount(1,"saabir",10000)
b2=BankAccount(1,"ayesha",13000)

In [16]:
b1.deposit(10000)


deposited suceesfully
20000


In [17]:
b1.name

'saabir'

In [18]:
# inheritance in python
# single class inheritance
class transaction(BankAccount):
    def __init__(self,i,name,balance,amount,credit):
        super().__init__(i,name,balance)
        self.amount=amount
        self.credit=credit
    def printl(self):
        print(self.i,self.balance,self.amount,self.credit,self.name)


In [19]:
t1=transaction(12,"saabir",100000,10000,True)

In [20]:
t1.printl()

12 100000 10000 True saabir


In [21]:
t1.deposit(10000)

deposited suceesfully
110000


In [22]:
t1.printbalance()

110000


In [23]:
class data:
    def __init__(self,dname,data1):
        self.dname=dname
        self.data1=data1
    def printdata():
        print(self.dname,self.data1)


In [24]:
#multipple inhertiance
# when a class nherits more than one base class
class Item(data):
    def __init__(self,name,Price,Size,data1,dname):
        data.__init__(self,dname,data1)
        self.name=name
        self.Price=Price
        self.Size=Size
    def printdetails(self):
        print(self.name,self.Price,self.Size)
I1=Item("butter",20,"M",30,"KB")
I1.printdetails()

butter 20 M


In [25]:
class customer(data):
    def __init__(self,cname,dname,data1):
        data.__init__(self,dname,data1)
        self.cname=cname
    def printcname(self):
        print(self.cname)
C1=customer("saabir","MB",45)
C1.printcname()

saabir


In [26]:
class Order(Item,customer):
    def __init__(self,name,Price,Size,cname,order_id,data1,dname):
        Item.__init__(self,name,Price,Size,data1,dname)
        customer.__init__(self,cname,data1,dname)
        #data.__init__(self,data1,dname)
        self.order_id=order_id
    def printdetails(self):
        print(self.name,self.Price,self.Size,self.order_id,self.cname,self.data1,self.dname)
O1=Order("butter",20,"M","saabir",23,67,"GB")

In [27]:
O1.printdetails()

butter 20 M 23 saabir GB 67


In [28]:
# polymorphism
# method overriding
# it is a method to overwrite a specific implemeantaion of a parent class
class Animal:
    def speak(self):
        return "sound of an animal"
A1=Animal()
A1.speak()

'sound of an animal'

In [29]:
class dog(Animal):
    def speak(self):
        return " woof!"

D1=dog()
D1.speak()

' woof!'

In [30]:
class cat(dog):
    def speak(self):
        return "Meow"
c1=cat()
c1.speak()

'Meow'

In [31]:
#funnction form of class which demostartes polymorphism
def animal(Animal):
    print(Animal.speak())
animal(D1)# we have to give parameter as objects creates not class name

 woof!


In [32]:
import math

In [33]:
class shape:
    def area(self):
        print("area of a shape")
class square(shape):
    def __init__(self,side):
        self.side=side
    def area(self):
        print(self.side*self.side)
class circle(shape):
    def __init__(self,radius):
        self.radius=radius
    def area(self):
        print(self.radius*self.radius*math.pi)
s1=square(23)
c1=circle(3)
#method overriding

In [34]:
#function opearting polymorphism
def Area(shape):
    shape.area()
Area(s1)
Area(c1)

529
28.274333882308138


In [35]:
# polymorphisn with abstract base class along with functions and methods 
#In python interfaces is abstract base class
#polymoriphism is abstract base class
# abstarct base class is used to define common methods for the group of classes 
#It is used to enforce the common methods into derived class to maintain consitanty in the derived classes



In [36]:
from abc import ABC,abstractmethod
# define a abstract class
class vehicle(ABC):
    @abstractmethod
    def startengine(self):
        #since it is abstract class it needs to be empty
        pass
class car(vehicle):
    # abstract method enforces the commom methods if the commom methods are not implemented then it shows an error
    #while creating an object
    def startengine(self):
        print("start engine")

In [37]:
C1=car()
C1.startengine()

start engine


In [38]:
# encapsulation and abstarction
# emcapsulation getter and setter
# public , protected and private variables or access modifiers
class Person:
    def __init__(self,name,age):
        self.name=name
        self.age=age# public variable
P1=Person("Saabir",34)
    
dir(P1)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'age',
 'name']

In [39]:
class Person:
    def __init__(self,name,age,gender):
        self.__name=name# private variables
        self.__age=age# private variables it cannot be access outsidde the class
        self.gender=gender#public variable
P1=Person("ayesha",23,"Female")
# we are retricting some of the attributes in the class

P1._Person__name="saabir"
print(P1._Person__name)
#dir(P1)

saabir


In [40]:
class Person:
    def __init__(self,name,age,gender):
        self._name=name# protected variables
        self._age=age# protected variables it cannot be access outside the class except the derived class
        self.gender=gender#public variable
P1=Person("ayesha",23,"Female")
# we are retricting some of the attributes in the class
class student(Person):
    def __init__(self,name,age,gender,year):
        Person.__init__(self,name,age,gender)
        self.year=year
    def print(self):
        print(self._name,self._age,self.gender,self.year)
s1=student("arfa",45,"Male",2003)
s1.print()
#s1._name="arfa1"

#dir(P1)

arfa 45 Male 2003


In [41]:
#encapsulation with getter and setter
class Person:
    def __init__(self,name,age):
        self.__name=name
        self.__age=age
    def get_details(self):#getter and setter function
        print(self.__name)
        print(self.__age)
    def set_name(self,name):
        self.__name=name
    def set_age(self,age):
        self.__age=age


In [42]:
# abstraction
# it is process of hiding complex implementation details and showing only nessary data
class vehicle:
    def drive(self):
        print("the vehicle is working")
    @abstractmethod
    def year(self):
        pass
class car(vehicle):
    def __init__(self,year):
        self.year=year
    def show_year(self):
        print("the year is ",self.year)
c1=car(2003)

In [43]:
c1.show_year()

the year is  2003


In [44]:
dir(c1)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'drive',
 'show_year',
 'year']

#magic methods

they are also known as dunder methos also known as doule underscore methods
They are just operations such as arithmetic , multiplication , division , subtraction, 
we can view available methos in dir(object name)


# operator overloading
common overloading magic methods
__add__ adds two numbers
__sub__subtrsctes two numbers
__mul__ multiplies two numbers
__eq__ checks if two operations are equal or not
__lt__ it is a less than operator


In [45]:
# the code prints all the directory of int class
dir(int)


['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'is_integer',
 

In [46]:
class Vector:
    def __init__(self,x,y):
        self.x=x
        self.y=y
    def __add__(self,other):
        print(self.x+other.x,self.y+other.y)
v1=Vector(2,3)
v2=Vector(4,7)
v1+v2

6 10


In [47]:

# custom exception handler
class DOBexception(Exception):
    def __init__(self,age):
        self.age=age
    pass
age=int(input("enter your age:-"))
try :
    if age<0:
        raise DOBexception(age)
    else:
        print("input taken")
except DOBexception:
    print("age cannot be negative",DOBexception(age))
finally:
    print("run cell again to enter age")

enter your age:- 4


input taken
run cell again to enter age


In [48]:
# iterators are used for advanded looping and memory managements
# they are used to loop the list sequentially without showing underlying structure
l=[1,2,3,4,4,5,6]
iterators=iter(l)
print(type(iterators))

<class 'list_iterator'>


In [49]:
print(iterators)# lazy loading techiniques unless when iterate to all elements

In [50]:
print(next(iterators))

1


In [51]:
try:
    print(next(iterators))
except StopIteration:
    print("The elements are no more")


2


In [52]:
#genarators
#geneartors are easy way to to implement iterators
#they use yeild function function to get the elements without wasting any memory
#they generate values on fly
def square(n):
    for i in range(3):
        yield i**2# this just directly passes the function into the loop
square(3)
#this creates a local variable and returns the function

<generator object square at 0x7b0f5ed1e0c0>

In [53]:
a=square(3)
next(a)

0

In [54]:
next(a)

1

In [55]:
for i in square(3):
    print(i)

0
1
4


In [56]:
def ger():
    yield 1
    yield 2
    yield 3
g=ger()

In [57]:
next(g)# returns the values one by one

1

In [58]:
#practical examples reading large files


In [59]:
# function decorators function copy, and closure
#decorator are used to change or modify the behavoir of function without modifiing the actual code 
#function copy
def func():
    print("function copy")
func()

function copy


In [60]:
funcopy=func
func()
print("before deleting")
del func
print("after deleting")
funcopy()

function copy
before deleting
after deleting
function copy


In [61]:
#closure which means function inside a function
def funct(pri):
    pri("this is inside a function")
funct(print)
# function as a parameter and an argument

this is inside a function


In [62]:
# function to print length of list
def functio(func):
    print("Welcome to the function")
    func()
    print("This is the end of the function")
#functio(len([1,2,3,4]))

In [63]:
@functio
def add():
    print("this is another function in add")
# this function will go in as a parameter
# decorators are used to modity or add functionality 
#without changing the existing code

Welcome to the function
this is another function in add
This is the end of the function


In [64]:
def function1(func):
    def wapper():
        print("something before the function")
        func()
        print("something after the function")
    return wapper()

@function1# this is decorator function where the add
#function goes in as a parameter
def add(a=3,d=5):
    print(a+d)


something before the function
8
something after the function


# numpy tutorials


In [2]:
import numpy as np

In [3]:
arr1=np.array([1,2,3,4])
print(arr1)
print(arr1.shape)

[1 2 3 4]
(4,)


In [4]:
arr2=np.array([[1,2,3,4,5,6]])
print(arr2)
print(arr2.reshape(3,2))

[[1 2 3 4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [5]:
print(arr2.reshape(3,2).T)

[[1 3 5]
 [2 4 6]]


In [6]:
print(arr2.reshape(3,2).T@arr2.reshape(3,2))

[[35 44]
 [44 56]]


In [7]:
sys=arr2.reshape(3,2).T@arr2.reshape(3,2)

In [8]:
print(np.linalg.inv(sys))

[[ 2.33333333 -1.83333333]
 [-1.83333333  1.45833333]]


In [9]:
print(np.linalg.inv(sys)@sys)

[[1.00000000e+00 5.32907052e-15]
 [1.15463195e-14 1.00000000e+00]]


In [10]:
np.linalg.solve(sys,[[1],[0]])

array([[ 2.33333333],
       [-1.83333333]])

In [11]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [12]:
np.ones((3,4))# used in deep learning to initiate the matrix quickly

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.eye(4,4)# tdentidy matrix 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
print(sys-np.eye(2,2))

[[34. 44.]
 [44. 55.]]


In [15]:

print(sys)
sys.shape
print(sys.ndim)
print(sys.size)
print(sys.dtype)
print(sys.itemsize)

[[35 44]
 [44 56]]
2
4
int64
8


In [16]:
# numpy vectories opeartions
v1=np.array([1,2,3,4,4])
v2=np.array([1,2,3,4,4])
print(v1+v2)

[2 4 6 8 8]


In [18]:
print(np.sqrt(v1))
print(np.exp(v2))
print(np.log(v2))
# universal functions

[1.         1.41421356 1.73205081 2.         2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003 54.59815003]
[0.         0.69314718 1.09861229 1.38629436 1.38629436]


In [19]:
arr3=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
arr3[1:,2:]# rows, columns like 1 dimentianl, 2 dimenatiional, more dimentional

array([[ 7,  8],
       [11, 12]])

In [22]:
# statiscl normalizeion concepts
# to have mean of 0 and sd of 1
#apply formula for methods
# logical methods
data=np.array([1,2,3,4,5,6,7,7,8,9])
data[data>5]# very very important

array([6, 7, 7, 8, 9])

In [24]:
data[(data>5) & (data<8)]

array([6, 7, 7])

# list and perform all linalg opreations

# pandas dataframe and series

In [ ]:
import pandas as pd


# logging

In [2]:
import logging
logging.basicConfig(level=logging.DEBUG)

logging.debug("this is debug message")

logging.info("this is info message")
logging.warning("this is warning message")
logging.error("this is error message")
logging.critical("this is critical message")


DEBUG:root:this is debug message
INFO:root:this is info message
ERROR:root:this is error message
CRITICAL:root:this is critical message


In [1]:
import logging
logging.basicConfig(
    level=logging.DEBUG,
    format='%(asctime)s-%(name)s-%(levelname)s-%(message)s',
    datefmt='%Y-%M-%d %H:%M:%S'
)

logging.debug("this is debug message")

logging.info("this is info message")
logging.warning("this is warning message")
logging.error("this is error message")
logging.critical("this is critical message")


2026-53-02 10:53:29-root-DEBUG-this is debug message
2026-53-02 10:53:29-root-INFO-this is info message
2026-53-02 10:53:29-root-WARNING-this is warning message
2026-53-02 10:53:29-root-ERROR-this is error message
2026-53-02 10:53:29-root-CRITICAL-this is critical message
